name = "wispy-lake-c00f"  # The name of your worker project
type = "javascript"  # The type of your worker (javascript, rust, etc.)

compatibility_date = "2024-11-28" 

# You can use workers.dev without specifying a custom route or subdomain
[env.production]
workers_dev = true  # Use workers_dev to access the worker without a custom route
route = ""  # Leave route empty if you're using the default workers.dev subdomain
zone_id = ""  # You can leave zone_id empty if not using a custom domain

[build]
command = ""  # The build command (if you're using dependencies)

[[kv_namespaces]]
binding = "MY_KV_NAMESPACE"  # (Optional) If you're using KV storage
id = "your_kv_namespace_id"  # (Optional) Replace with your KV namespace ID
