name = "wispy-lake-c00f"
main = "index.js"
compatibility_date = "2024-11-28"

# Add a route to bind this worker to a specific domain or subdomain
route = "*"
account_id = "4806f2425c6560e67d083f843b83dd5d"
